/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LngRouteRouteImport } from './routes/$lng/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LngIndexRouteImport } from './routes/$lng/index'

const LngRouteRoute = LngRouteRouteImport.update({
  id: '/$lng',
  path: '/$lng',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LngIndexRoute = LngIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LngRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lng': typeof LngRouteRouteWithChildren
  '/$lng/': typeof LngIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lng': typeof LngIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lng': typeof LngRouteRouteWithChildren
  '/$lng/': typeof LngIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$lng' | '/$lng/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$lng'
  id: '__root__' | '/' | '/$lng' | '/$lng/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LngRouteRoute: typeof LngRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lng': {
      id: '/$lng'
      path: '/$lng'
      fullPath: '/$lng'
      preLoaderRoute: typeof LngRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lng/': {
      id: '/$lng/'
      path: '/'
      fullPath: '/$lng/'
      preLoaderRoute: typeof LngIndexRouteImport
      parentRoute: typeof LngRouteRoute
    }
  }
}

interface LngRouteRouteChildren {
  LngIndexRoute: typeof LngIndexRoute
}

const LngRouteRouteChildren: LngRouteRouteChildren = {
  LngIndexRoute: LngIndexRoute,
}

const LngRouteRouteWithChildren = LngRouteRoute._addFileChildren(
  LngRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LngRouteRoute: LngRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
